/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.Teste.InterfaceUsuario;

import br.edu.ifnmg.Teste.DataAccess.BD;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author petronio
 */
public class frmVisualizarRelatorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmVisualizarRelatorio
     */
    public frmVisualizarRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jButton1)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jButton1)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection conexao;
        try {
            Map parameterMap = new HashMap();

            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager
                    .getConnection("jdbc:mysql://localhost:3306/teste", "root", "12345");

            URL arquivo = getClass().getResource("RelatorioTeste.jrxml");
            JasperViewer jrviewer = loadJrxml(arquivo, parameterMap, conexao);
            jrviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(frmVisualizarRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BD.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    private JasperViewer loadJasper(URL arquivo, Map parameterMap, Connection conexao) throws JRException {

        JasperReport jasperReport = (JasperReport) JRLoader.loadObject(arquivo);
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameterMap, conexao);
        JasperViewer jrviewer = new JasperViewer(jasperPrint, false);
        return jrviewer;
    }

    private JasperViewer loadJrxml(URL arquivo, Map parameterMap, Connection conexao) throws JRException {

        JasperDesign jasperDesign = JRXmlLoader.load(arquivo.getFile());
        JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameterMap, conexao);
        JasperViewer jrviewer = new JasperViewer(jasperPrint, false);
        return jrviewer;
    }
}
